baseURL = 'https://mjsmagalhaes.github.io'
languageCode = 'en-us'
title = 'MJSM Workshop'
theme = 'hugo-theme-hello-friend-ng'

[params]
 homeSubtitle = 'My DataScience adventures'
 disableReadOtherPosts = false

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "notebooks"
    name       = "Notebooks"
    url        = "notebook/"